# Generated by Django 4.2.26 on 2025-12-02 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprendices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aprendiz',
            old_name='documento',
            new_name='documento_identidad',
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='ciudad',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='correo',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='telefono',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
