# Generated by Django 4.2.26 on 2025-12-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_identidad', models.CharField(max_length=20, unique=True)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('TI', 'Tarjeta de Identidad'), ('PP', 'Pasaporte')], default='CC', max_length=3)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=100)),
                ('fecha_nacimiento', models.DateField(auto_now=True)),
                ('ciudad', models.CharField(max_length=100)),
                ('nivel_educacion', models.CharField(choices=[('TEC', 'Técnico'), ('TGL', 'Tecnólogo'), ('PRE', 'Pregrado'), ('ESP', 'Especialización'), ('MAE', 'Maestría'), ('DOC', 'Doctorado')], max_length=3)),
                ('especialidad', models.CharField(max_length=100)),
                ('anos_experiencia', models.PositiveIntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_vinculacion', models.DateField()),
                ('fecha_registro', models.DateField(auto_now=True)),
            ],
        ),
    ]
