# Generated by Django 4.2.26 on 2025-12-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='nivel_educacion',
        ),
        migrations.AddField(
            model_name='instructor',
            name='direccion',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='nivel_educativo',
            field=models.CharField(choices=[('TEC', 'Técnico'), ('TGL', 'Tecnólogo'), ('PRE', 'Pregrado'), ('ESP', 'Especialización'), ('MAE', 'Maestría'), ('DOC', 'Doctorado')], default='MAE', max_length=3),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='ciudad',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='correo',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='telefono',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('TI', 'Tarjeta de Identidad'), ('PAS', 'Pasaporte')], default='CC', max_length=3),
        ),
    ]
